/**
 * Cloudflare Pages Function — real HTTP 301 for exact SEO stubs.
 * Generated by scripts/sync-host-redirects.mjs. Do not edit by hand.
 *
 * Lovable's CDN currently ignores this file (and public/_redirects).
 * It is here so a Cloudflare Pages (or Workers) deploy emits real 301s.
 */
const EXACT = {
  "/exercise-hub": "/exercises",
  "/about-us": "/about",
  "/trust-credibility": "/trust",
  "/privacy-policy": "/privacy",
  "/cookies-policy": "/cookies",
  "/terms-conditions": "/terms",
  "/zakat": "/zakat-appeal",
  "/es/corporate-partnerships": "/corporate-partnerships",
  "/fr/corporate-partnerships": "/corporate-partnerships",
  "/de/corporate-partnerships": "/corporate-partnerships",
  "/pt/corporate-partnerships": "/corporate-partnerships",
  "/blog/nhs-arthritis-exercises": "/blog/arthritis-exercises-uk-clinical",
  "/blog/nhs-rheumatology-waiting-times-uk": "/blog/rheumatology-waiting-times-uk",
  "/blog/knee-osteoarthritis-exercises": "/blog/knee-arthritis-exercises-uk",
  "/blog/knee-exercises-arthritis": "/blog/knee-arthritis-exercises-uk",
  "/blog/food-supplements-for-joint-pain": "/blog/best-supplements-joint-pain",
  "/blog/arthritis-medication-uk": "/blog/arthritis-medication-guide",
  "/blog/arthritis-and-weight-management-uk": "/blog/weight-management-arthritis-evidence",
  "/blog/swimming-for-arthritis-uk": "/blog/swimming-for-arthritis",
  "/blog/turmeric-for-arthritis-uk": "/blog/turmeric-for-arthritis",
  "/blog/mindfulness-meditation-chronic-pain": "/blog/mindfulness-chronic-pain-arthritis-guide",
  "/blog/vitamin-d-arthritis-uk-risk": "/blog/vitamin-d-arthritis-uk",
  "/blog/arthritis-and-cold-weather-uk": "/blog/cold-weather-arthritis-uk-winter",
  "/blog/cold-weather-and-arthritis": "/blog/cold-weather-arthritis-uk-winter",
  "/blog/arthritis-and-sleep-uk": "/blog/how-to-sleep-with-arthritis-uk",
  "/blog/glucosamine-vs-collagen-arthritis": "/blog/glucosamine-vs-collagen",
  "/blog/hand-arthritis-exercises-uk": "/blog/hand-exercises-for-arthritis",
  "/blog/arthritis-and-mental-health": "/blog/arthritis-and-mental-health-uk",
  "/blog/arthritis-diet-myths-debunked": "/blog/arthritis-and-diet-myths-uk",
  "/blog/arthritis-fatigue-management": "/blog/arthritis-fatigue-management-uk",
  "/arthritis-support/stockport": "/arthritis-support/manchester",
  "/arthritis-support/stirling": "/arthritis-support/glasgow",
  "/arthritis-support/winchester": "/arthritis-support/southampton",
  "/arthritis-support/bradford": "/arthritis-support/leeds",
  "/arthritis-support/milton-keynes": "/arthritis-support/cambridge",
  "/arthritis-support/oswestry": "/arthritis-support/stoke-on-trent",
  "/arthritis-support/shrewsbury": "/arthritis-support/wolverhampton",
  "/es/404": "/",
  "/fr/404": "/",
  "/de/404": "/",
  "/pt/404": "/",
  "/exercises/swimming-for-knee": "/exercises/swimming-for-knee-arthritis",
  "/exercises/swimming-for-hip": "/exercises/swimming-for-hip-arthritis",
  "/exercises/swimming-for-shoulder": "/exercises/swimming-for-shoulder-arthritis",
  "/exercises/swimming-for-hand": "/exercises/swimming-for-hand-arthritis",
  "/exercises/swimming-for-back": "/exercises/swimming-for-back-arthritis",
  "/exercises/swimming-for-ankle": "/exercises/swimming-for-ankle-arthritis",
  "/exercises/yoga-for-knee": "/exercises/yoga-for-knee-arthritis",
  "/exercises/yoga-for-hip": "/exercises/yoga-for-hip-arthritis",
  "/exercises/yoga-for-shoulder": "/exercises/yoga-for-shoulder-arthritis",
  "/exercises/yoga-for-hand": "/exercises/yoga-for-hand-arthritis",
  "/exercises/yoga-for-back": "/exercises/yoga-for-back-arthritis",
  "/exercises/yoga-for-ankle": "/exercises/yoga-for-ankle-arthritis",
  "/exercises/cycling-for-knee": "/exercises/cycling-for-knee-arthritis",
  "/exercises/cycling-for-hip": "/exercises/cycling-for-hip-arthritis",
  "/exercises/cycling-for-shoulder": "/exercises/cycling-for-shoulder-arthritis",
  "/exercises/cycling-for-hand": "/exercises/cycling-for-hand-arthritis",
  "/exercises/cycling-for-back": "/exercises/cycling-for-back-arthritis",
  "/exercises/cycling-for-ankle": "/exercises/cycling-for-ankle-arthritis",
  "/exercises/walking-for-knee": "/exercises/walking-for-knee-arthritis",
  "/exercises/walking-for-hip": "/exercises/walking-for-hip-arthritis",
  "/exercises/walking-for-shoulder": "/exercises/walking-for-shoulder-arthritis",
  "/exercises/walking-for-hand": "/exercises/walking-for-hand-arthritis",
  "/exercises/walking-for-back": "/exercises/walking-for-back-arthritis",
  "/exercises/walking-for-ankle": "/exercises/walking-for-ankle-arthritis",
  "/exercises/tai-chi-for-knee": "/exercises/tai-chi-for-knee-arthritis",
  "/exercises/tai-chi-for-hip": "/exercises/tai-chi-for-hip-arthritis",
  "/exercises/tai-chi-for-shoulder": "/exercises/tai-chi-for-shoulder-arthritis",
  "/exercises/tai-chi-for-hand": "/exercises/tai-chi-for-hand-arthritis",
  "/exercises/tai-chi-for-back": "/exercises/tai-chi-for-back-arthritis",
  "/exercises/tai-chi-for-ankle": "/exercises/tai-chi-for-ankle-arthritis",
  "/exercises/pilates-for-knee": "/exercises/pilates-for-knee-arthritis",
  "/exercises/pilates-for-hip": "/exercises/pilates-for-hip-arthritis",
  "/exercises/pilates-for-shoulder": "/exercises/pilates-for-shoulder-arthritis",
  "/exercises/pilates-for-hand": "/exercises/pilates-for-hand-arthritis",
  "/exercises/pilates-for-back": "/exercises/pilates-for-back-arthritis",
  "/exercises/pilates-for-ankle": "/exercises/pilates-for-ankle-arthritis",
  "/exercises/stretching-for-knee": "/exercises/stretching-for-knee-arthritis",
  "/exercises/stretching-for-hip": "/exercises/stretching-for-hip-arthritis",
  "/exercises/stretching-for-shoulder": "/exercises/stretching-for-shoulder-arthritis",
  "/exercises/stretching-for-hand": "/exercises/stretching-for-hand-arthritis",
  "/exercises/stretching-for-back": "/exercises/stretching-for-back-arthritis",
  "/exercises/stretching-for-ankle": "/exercises/stretching-for-ankle-arthritis",
  "/exercises/strength-training-for-knee": "/exercises/strength-training-for-knee-arthritis",
  "/exercises/strength-training-for-hip": "/exercises/strength-training-for-hip-arthritis",
  "/exercises/strength-training-for-shoulder": "/exercises/strength-training-for-shoulder-arthritis",
  "/exercises/strength-training-for-hand": "/exercises/strength-training-for-hand-arthritis",
  "/exercises/strength-training-for-back": "/exercises/strength-training-for-back-arthritis",
  "/exercises/strength-training-for-ankle": "/exercises/strength-training-for-ankle-arthritis"
};

function normalizePath(pathname) {
  if (!pathname) return "/";
  const collapsed = pathname.replace(/\/{2,}/g, "/");
  if (collapsed.length > 1 && collapsed.endsWith("/")) return collapsed.slice(0, -1);
  return collapsed || "/";
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const path = normalizePath(url.pathname);
  const dest = EXACT[path];
  if (!dest) return context.next();
  const location = dest + url.search;
  return new Response(null, {
    status: 301,
    headers: {
      Location: location,
      "Cache-Control": "public, max-age=3600",
    },
  });
}
