// BATCH: Copy each section into its own file (PainManagementHub.tsx, ExerciseHub.tsx, etc.)

// ============================================================================
// 1. PainManagementHub.tsx
// ============================================================================
import React from 'react';
import ClusterHub from './ClusterHub';
export default function PainManagementHub() {
  return <ClusterHub clusterSlug="pain-management" clusterName="Arthritis Pain & Symptom Management" clusterDescription="Comprehensive strategies for managing arthritis pain without relying solely on medication." pillarArticleSlug="arthritis-pain-management" pillarArticleTitle="Arthritis Pain Management: Complete Guide to Relief" statsKeywords={52} statsTraffic="1,000-1,500/mo" statsSnippets={8} articles={[{slug:'joint-pain-science',title:'Joint Pain Science: Why Arthritis Hurts',description:'Understanding the mechanisms of arthritis pain.',keywords:['pain','nerve','inflammation']},{slug:'acute-vs-chronic',title:'Acute Pain vs Chronic Pain Management',description:'Different approaches for acute and chronic pain.',keywords:['acute','chronic','pain']},{slug:'pain-relief-no-meds',title:'Pain Relief Without Medication',description:'Non-pharmaceutical pain management strategies.',keywords:['non-drug','natural','alternatives']},{slug:'natural-pain-remedies',title:'Natural Remedies for Arthritis Pain',description:'Herbal and natural approaches to pain management.',keywords:['natural','herbal','remedies']},{slug:'heat-cold-therapy',title:'Heat & Cold Therapy: When to Use Each',description:'Choosing between heat and cold for pain relief.',keywords:['heat','cold','therapy']},{slug:'night-pain',title:'Arthritis Pain at Night: Sleep Solutions',description:'Managing pain to improve sleep quality.',keywords:['night pain','sleep','insomnia']},{slug:'pain-medications',title:'Pain Medication Side Effects & Safety',description:'Understanding risks and benefits of pain medications.',keywords:['medications','side effects','safety']},{slug:'topical-relief',title:'Topical Pain Relief: Creams & Gels',description:'Using topical treatments for local pain relief.',keywords:['topical','creams','gels']},{slug:'injections',title:'Injection Therapies: Steroids & Hyaluronic Acid',description:'Joint injections for pain and inflammation.',keywords:['injections','steroids','hyaluronic']},{slug:'nerve-pain',title:'Nerve Pain in Arthritis',description:'Managing neuropathic pain related to arthritis.',keywords:['nerve pain','neuropathy','pain']},{slug:'weather-pain',title:'Weather & Arthritis Pain',description:'Why arthritis pain changes with weather.',keywords:['weather','barometric','pain']},{slug:'pain-mindset',title:'Pain Catastrophizing: Mental Strategies',description:'Cognitive approaches to managing pain perception.',keywords:['mental','mindset','catastrophizing']}]} />;
}

// ============================================================================
// 2. ExerciseHub.tsx
// ============================================================================
export default function ExerciseHub() {
  return <ClusterHub clusterSlug="exercise" clusterName="Exercise & Physical Activity" clusterDescription="Learn how to stay active and build strength safely with arthritis." pillarArticleSlug="arthritis-exercises" pillarArticleTitle="Arthritis Exercises: Safe Movement & Strength Building" statsKeywords={48} statsTraffic="1,100-1,600/mo" statsSnippets={7} articles={[{slug:'safe-exercises',title:'Safe Arthritis Exercises: Beginner Guide',description:'Starting an exercise program with arthritis.',keywords:['exercises','beginner','safe']},{slug:'range-motion',title:'Range of Motion Exercises',description:'Exercises to maintain and improve flexibility.',keywords:['flexibility','range','mobility']},{slug:'strength-training',title:'Strength Training with Arthritis',description:'Building muscle strength safely.',keywords:['strength','resistance','training']},{slug:'low-impact-cardio',title:'Low-Impact Cardio for Arthritis',description:'Cardiovascular exercise without joint stress.',keywords:['cardio','aerobic','low-impact']},{slug:'swimming',title:'Swimming: Best Exercise for Joints',description:'Why swimming is ideal for arthritis.',keywords:['swimming','water','exercise']},{slug:'walking-programs',title:'Walking Programs: Pace & Duration',description:'Safe walking strategies for arthritis.',keywords:['walking','pace','duration']},{slug:'yoga-arthritis',title:'Yoga for Arthritis: Poses & Modifications',description:'Arthritis-friendly yoga poses.',keywords:['yoga','poses','flexibility']},{slug:'pilates-core',title:'Pilates for Core Strength',description:'Core stability exercises for arthritis.',keywords:['pilates','core','stability']},{slug:'therapy-vs-self',title:'Physical Therapy vs Self-Exercise',description:'When to seek professional guidance.',keywords:['PT','therapy','guidance']},{slug:'warm-up',title:'Warming Up: Pre-Exercise Routines',description:'Preparing joints before exercise.',keywords:['warm up','prep','routines']},{slug:'post-exercise',title:'Post-Exercise Pain: When to Rest',description:'Managing pain after exercise.',keywords:['pain','rest','recovery']},{slug:'progression',title:'Exercise Progression: Building Capacity',description:'Gradually increasing exercise intensity.',keywords:['progression','building','capacity']}]} />;
}

// ============================================================================
// 3. NutritionHub.tsx
// ============================================================================
export default function NutritionHub() {
  return <ClusterHub clusterSlug="nutrition" clusterName="Diet, Nutrition & Lifestyle" clusterDescription="Explore how diet and lifestyle choices can reduce arthritis symptoms." pillarArticleSlug="arthritis-diet-nutrition" pillarArticleTitle="Arthritis Diet & Nutrition: Complete Guide" statsKeywords={42} statsTraffic="700-1,000/mo" statsSnippets={5} articles={[{slug:'anti-inflammatory',title:'Anti-Inflammatory Diet for Arthritis',description:'Foods that reduce inflammation.',keywords:['anti-inflammatory','diet','foods']},{slug:'foods-avoid',title:'Foods to Avoid with Arthritis',description:'Which foods may worsen arthritis.',keywords:['avoid','trigger','inflammation']},{slug:'omega3',title:'Omega-3 & Joint Health',description:'How omega-3 fatty acids help arthritis.',keywords:['omega-3','fish oil','joints']},{slug:'vitamin-d',title:'Vitamin D & Bone Health',description:'Why vitamin D matters for arthritis.',keywords:['vitamin D','bone','calcium']},{slug:'turmeric',title:'Turmeric & Curcumin Evidence',description:'What science says about turmeric.',keywords:['turmeric','curcumin','spices']},{slug:'mediterranean',title:'Mediterranean Diet for RA',description:'The Mediterranean diet for rheumatoid arthritis.',keywords:['Mediterranean','diet','RA']},{slug:'weight-management',title:'Weight Management & Joint Stress',description:'How weight affects arthritis symptoms.',keywords:['weight','obesity','joints']},{slug:'gut-health',title:'Gut Health & Arthritis',description:'Connection between gut microbiome and arthritis.',keywords:['gut','microbiome','health']},{slug:'probiotics',title:'Probiotics & Autoimmune Disease',description:'Role of probiotics in autoimmune arthritis.',keywords:['probiotics','autoimmune','gut']},{slug:'hydration',title:'Hydration & Joint Lubrication',description:'Why water is important for joints.',keywords:['hydration','water','joints']},{slug:'alcohol',title:'Alcohol & Arthritis Medication Interactions',description:'Safety of alcohol with arthritis medications.',keywords:['alcohol','interactions','safety']},{slug:'meal-planning',title:'Meal Planning with Arthritis',description:'Practical meal planning strategies.',keywords:['meal planning','recipes','practical']}]} />;
}

// ============================================================================
// 4. MentalHealthHub.tsx, ArthritisTypesHub.tsx, TreatmentsHub.tsx, LivingWellHub.tsx
// Follow same pattern - create individual files with similar structure
// ============================================================================
