import { useState, useMemo } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Calendar, Download, Dumbbell, CheckCircle } from "lucide-react";
import { exerciseJointPages, type ExerciseJointPage } from "@/data/exerciseJointMatrix";

const allJoints = ["knee", "hip", "shoulder", "hand", "back", "ankle"] as const;
const jointLabels: Record<string, string> = { knee: "Knee", hip: "Hip", shoulder: "Shoulder", hand: "Hand", back: "Back", ankle: "Ankle" };

const fitnessLevels = [
  { id: "beginner", label: "Beginner", desc: "New to exercise or recovering" },
  { id: "intermediate", label: "Intermediate", desc: "Some regular activity" },
  { id: "active", label: "Active", desc: "Exercise 4+ times per week" },
] as const;

const goals = [
  { id: "pain", label: "Pain Relief", desc: "Gentle exercises to reduce pain" },
  { id: "mobility", label: "Improve Mobility", desc: "Increase range of motion" },
  { id: "strength", label: "Build Strength", desc: "Strengthen muscles around joints" },
] as const;

const goalExerciseMap: Record<string, string[]> = {
  pain: ["stretching", "yoga", "tai-chi", "swimming"],
  mobility: ["yoga", "swimming", "pilates", "stretching"],
  strength: ["strength-training", "pilates", "cycling", "walking"],
};

const dayNames = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

type Step = "joints" | "fitness" | "goal" | "plan";

export default function ExercisePlanGenerator() {
  const [step, setStep] = useState<Step>("joints");
  const [selectedJoints, setSelectedJoints] = useState<string[]>([]);
  const [fitness, setFitness] = useState<string>("beginner");
  const [goal, setGoal] = useState<string>("pain");

  const toggleJoint = (joint: string) => {
    setSelectedJoints((prev) =>
      prev.includes(joint) ? prev.filter((j) => j !== joint) : [...prev, joint]
    );
  };

  const plan = useMemo(() => {
    if (step !== "plan" || selectedJoints.length === 0) return [];

    const exerciseTypes = goalExerciseMap[goal] || goalExerciseMap.pain;
    const sessionsPerWeek = fitness === "beginner" ? 4 : fitness === "intermediate" ? 5 : 6;

    const relevantPages = exerciseJointPages.filter(
      (p) => selectedJoints.includes(p.joint) && exerciseTypes.includes(p.exercise)
    );

    const days: { day: string; isRest: boolean; exercises: { joint: string; exercise: string; instructions: { name: string; reps: string }[] }[] }[] = [];

    for (let d = 0; d < 7; d++) {
      if (d >= sessionsPerWeek) {
        days.push({ day: dayNames[d], isRest: true, exercises: [] });
        continue;
      }

      // Rotate joints and exercise types
      const jointForDay = selectedJoints[d % selectedJoints.length];
      const exerciseForDay = exerciseTypes[d % exerciseTypes.length];

      const page = relevantPages.find((p) => p.joint === jointForDay && p.exercise === exerciseForDay)
        || relevantPages.find((p) => p.joint === jointForDay)
        || relevantPages[d % Math.max(relevantPages.length, 1)];

      if (page) {
        const maxExercises = fitness === "beginner" ? 2 : fitness === "intermediate" ? 3 : 3;
        days.push({
          day: dayNames[d],
          isRest: false,
          exercises: [{
            joint: page.joint,
            exercise: page.exercise,
            instructions: page.instructions.slice(0, maxExercises),
          }],
        });
      } else {
        days.push({ day: dayNames[d], isRest: true, exercises: [] });
      }
    }
    return days;
  }, [step, selectedJoints, fitness, goal]);

  const downloadPlan = () => {
    const lines: string[] = [
      "PERSONALISED ARTHRITIS EXERCISE PLAN",
      "Generated by Living With Arthritis UK",
      `Joints: ${selectedJoints.map((j) => jointLabels[j]).join(", ")}`,
      `Fitness Level: ${fitness}`,
      `Goal: ${goal}`,
      "",
      "===================================",
      "",
    ];
    plan.forEach((day) => {
      lines.push(`📅 ${day.day}`);
      if (day.isRest) {
        lines.push("   Rest Day — gentle stretching or walking");
      } else {
        day.exercises.forEach((ex) => {
          lines.push(`   ${jointLabels[ex.joint]} — ${ex.exercise}`);
          ex.instructions.forEach((inst) => {
            lines.push(`   • ${inst.name}: ${inst.reps}`);
          });
        });
      }
      lines.push("");
    });
    lines.push("Disclaimer: This plan is for educational purposes. Consult your GP or physiotherapist before starting.");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "arthritis-exercise-plan.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  if (step === "joints") {
    return (
      <div className="space-y-6">
        <h3 className="text-lg font-bold text-foreground">Step 1: Select Your Affected Joints</h3>
        <p className="text-sm text-muted-foreground">Choose all joints where you experience pain or stiffness.</p>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {allJoints.map((joint) => (
            <button
              key={joint}
              onClick={() => toggleJoint(joint)}
              className={`px-4 py-4 rounded-xl border-2 transition-all cursor-pointer text-center ${
                selectedJoints.includes(joint)
                  ? "border-primary bg-primary/5 text-foreground"
                  : "border-border/30 bg-card hover:border-primary/30 text-muted-foreground"
              }`}
            >
              <Dumbbell className={`w-5 h-5 mx-auto mb-1.5 ${selectedJoints.includes(joint) ? "text-primary" : ""}`} />
              <span className="text-sm font-semibold">{jointLabels[joint]}</span>
            </button>
          ))}
        </div>
        <div className="flex justify-end">
          <Button onClick={() => setStep("fitness")} disabled={selectedJoints.length === 0} className="gap-1">
            Next <CheckCircle className="w-4 h-4" />
          </Button>
        </div>
      </div>
    );
  }

  if (step === "fitness") {
    return (
      <div className="space-y-6">
        <h3 className="text-lg font-bold text-foreground">Step 2: Your Fitness Level</h3>
        <div className="space-y-3">
          {fitnessLevels.map((level) => (
            <button
              key={level.id}
              onClick={() => setFitness(level.id)}
              className={`w-full text-left px-5 py-4 rounded-xl border-2 transition-all cursor-pointer ${
                fitness === level.id
                  ? "border-primary bg-primary/5"
                  : "border-border/30 bg-card hover:border-primary/30"
              }`}
            >
              <span className="text-sm font-semibold text-foreground">{level.label}</span>
              <p className="text-xs text-muted-foreground mt-0.5">{level.desc}</p>
            </button>
          ))}
        </div>
        <div className="flex justify-between">
          <Button variant="ghost" onClick={() => setStep("joints")}>Back</Button>
          <Button onClick={() => setStep("goal")}>Next</Button>
        </div>
      </div>
    );
  }

  if (step === "goal") {
    return (
      <div className="space-y-6">
        <h3 className="text-lg font-bold text-foreground">Step 3: Your Primary Goal</h3>
        <div className="space-y-3">
          {goals.map((g) => (
            <button
              key={g.id}
              onClick={() => setGoal(g.id)}
              className={`w-full text-left px-5 py-4 rounded-xl border-2 transition-all cursor-pointer ${
                goal === g.id
                  ? "border-primary bg-primary/5"
                  : "border-border/30 bg-card hover:border-primary/30"
              }`}
            >
              <span className="text-sm font-semibold text-foreground">{g.label}</span>
              <p className="text-xs text-muted-foreground mt-0.5">{g.desc}</p>
            </button>
          ))}
        </div>
        <div className="flex justify-between">
          <Button variant="ghost" onClick={() => setStep("fitness")}>Back</Button>
          <Button onClick={() => setStep("plan")} className="gap-1">Generate Plan <Calendar className="w-4 h-4" /></Button>
        </div>
      </div>
    );
  }

  // Plan view
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h3 className="text-lg font-bold text-foreground">Your 7-Day Exercise Plan</h3>
          <p className="text-xs text-muted-foreground mt-1">
            {selectedJoints.map((j) => jointLabels[j]).join(", ")} · {fitness} · {goal}
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={downloadPlan} className="gap-1.5">
          <Download className="w-4 h-4" /> Download
        </Button>
      </div>

      <div className="space-y-3">
        {plan.map((day) => (
          <Card key={day.day} className={`border-border/30 ${day.isRest ? "opacity-60" : ""}`}>
            <CardContent className="py-4">
              <div className="flex items-center gap-3">
                <Badge variant="outline" className="text-xs font-bold w-24 justify-center">{day.day}</Badge>
                {day.isRest ? (
                  <span className="text-sm text-muted-foreground italic">Rest day — gentle stretching or a short walk</span>
                ) : (
                  <div className="flex-1 space-y-2">
                    {day.exercises.map((ex, i) => (
                      <div key={i}>
                        <span className="text-sm font-semibold text-foreground capitalize">
                          {jointLabels[ex.joint]} — {ex.exercise.replace("-", " ")}
                        </span>
                        <ul className="mt-1 space-y-0.5">
                          {ex.instructions.map((inst, j) => (
                            <li key={j} className="text-xs text-muted-foreground flex items-start gap-1.5">
                              <span className="text-primary mt-0.5">•</span>
                              <span><strong>{inst.name}</strong> — {inst.reps}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <p className="text-xs text-muted-foreground text-center italic">
        This plan is for educational purposes only. Consult your GP or physiotherapist before starting any new exercise programme.
      </p>

      <div className="flex justify-center gap-3">
        <Button variant="outline" onClick={() => { setStep("joints"); }}>Start Over</Button>
      </div>
    </div>
  );
}
