// Curated list of routes to prerender into static HTML so JSON-LD,
// <title>, and meta are visible to crawlers and extractors that do
// NOT execute JavaScript (Rich Results Test, LinkedIn, Slack, etc).
//
// Keep this list to routes where SEO/social previews matter most.
// Dynamic auth/admin/result pages are intentionally excluded.

export const PRERENDER_ROUTES = [
  "/",
  "/about",
  "/blog",
  "/blog-hub",
  "/diet",
  "/diet/mediterranean-diet-for-arthritis",
  "/exercises",
  "/exercises/tai-chi-for-balance",
  "/exercises/tai-chi-for-arthritis",
  "/exercises/seated-tai-chi-for-arthritis",
  "/exercises/tai-chi-for-beginners",
  "/conditions/osteoarthritis",
  "/conditions/rheumatoid-arthritis",
  "/conditions/psoriatic-arthritis",
  "/conditions/gout",
  "/conditions/ankylosing-spondylitis",
  "/conditions/juvenile-arthritis",
  "/conditions/fibromyalgia",
  "/conditions/lupus",
  "/conditions/knee-arthritis",
  "/conditions/hand-arthritis",
  "/conditions/shoulder-arthritis",
  "/conditions/polymyalgia-rheumatica",
  "/conditions/reactive-arthritis",
  "/self-help",
  "/health-tools",
  "/ways-to-help",
  "/donate",
  "/zakat-appeal",
  "/corporate-giving",
  "/trust",
  "/community",
  "/governance",
  "/finances",
  "/impact",
  "/arthritis-flare-ups",
  "/myths/does-cracking-knuckles-cause-arthritis",
  "/guides/uk-arthritis",
  "/guides/exercise",
  "/guides/diet",
  "/guides/health-services",
  "/guides/benefits-pip",
  "/arthritis-waiting-list-help",
  "/tools/waiting-time",
  "/arthritis-support",
  "/privacy",
  "/cookies",
  "/terms",
  "/accessibility",
  "/safeguarding",
  "/complaints",
];
