/**
 * Lightweight JSON search over a baked static catalog (no Supabase).
 * Index: public/search-index.json (generated by scripts/generate-search-index.mjs).
 */

import bakedIndex from "../public/search-index.json";

export type SearchIndexItem = {
  id: string;
  title: string;
  href: string;
  excerpt: string;
  topic: string;
  wordCount: number;
  keywords?: string[];
};

export type SearchIndexFile = {
  generatedAt: string;
  version: number;
  items: SearchIndexItem[];
};

const TOPIC_ALIASES: Record<string, string> = {
  all: "All",
  "guides & hubs": "Guides & hubs",
  guides: "Guides & hubs",
  hubs: "Guides & hubs",
  exercise: "Exercise",
  exercises: "Exercise",
  nutrition: "Nutrition",
  diet: "Nutrition",
  health: "Health",
  lifestyle: "Lifestyle",
  supplements: "Supplements",
  treatment: "Treatment",
  treatments: "Treatment",
  "finances & benefits": "Finances & Benefits",
  finances: "Finances & Benefits",
  benefits: "Finances & Benefits",
  pip: "Finances & Benefits",
  "mental health": "Mental Health",
  "work & career": "Work & Career",
  work: "Work & Career",
  conditions: "Conditions",
  other: "Other",
};

function normalizeTopic(raw: string | undefined | null): string {
  if (!raw) return "All";
  const key = raw.trim().toLowerCase();
  return TOPIC_ALIASES[key] ?? raw;
}

function wordCountInBucket(count: number, words: string): boolean {
  if (!words || words === "any") return true;
  if (words === "under1000" || words === "under_1000") return count > 0 && count < 1000;
  if (words === "over1000" || words === "over_1000") return count >= 1000;
  return true;
}

export function getBakedSearchIndex(): SearchIndexFile {
  return bakedIndex as SearchIndexFile;
}

export async function loadSearchIndex(env: {
  ASSETS?: { fetch: (request: Request) => Promise<Response> };
}): Promise<SearchIndexItem[]> {
  if (env.ASSETS) {
    try {
      const res = await env.ASSETS.fetch(
        new Request("https://assets.local/search-index.json"),
      );
      if (res.ok) {
        const data = (await res.json()) as SearchIndexFile;
        if (Array.isArray(data.items) && data.items.length) return data.items;
      }
    } catch {
      // fall through to baked
    }
  }
  return getBakedSearchIndex().items;
}

/** Rank title / intent matches above weak excerpt-only hits. */
function scoreSearchItem(item: SearchIndexItem, q: string): number {
  if (!q) return 0;
  const title = item.title.toLowerCase();
  const excerpt = (item.excerpt || "").toLowerCase();
  const topic = (item.topic || "").toLowerCase();
  const keywords = (item.keywords || []).map((k) => k.toLowerCase());
  const tokens = q.split(/\s+/).filter(Boolean);

  let score = 0;
  if (title === q) score += 120;
  else if (title.startsWith(q)) score += 80;
  else if (title.includes(q)) score += 50;

  for (const token of tokens) {
    if (title.includes(token)) score += 14;
    if (keywords.some((k) => k.includes(token) || token.includes(k))) score += 8;
    if (topic.includes(token)) score += 4;
    if (excerpt.includes(token)) score += 2;
  }

  if (excerpt.includes(q)) score += 6;
  return score;
}

export function filterSearchItems(
  items: SearchIndexItem[],
  opts: { q?: string; topic?: string; words?: string },
): SearchIndexItem[] {
  const topic = normalizeTopic(opts.topic);
  const words = (opts.words || "any").trim().toLowerCase();
  const q = (opts.q || "").trim().toLowerCase();

  const filtered = items.filter((item) => {
    if (topic !== "All" && item.topic !== topic) return false;
    if (!wordCountInBucket(item.wordCount, words)) return false;
    if (!q) return true;
    const hay = [item.title, item.excerpt, item.topic, ...(item.keywords || [])]
      .join(" ")
      .toLowerCase();
    // Prefer full-phrase match; also allow all tokens present for multi-word intent.
    if (hay.includes(q)) return true;
    const tokens = q.split(/\s+/).filter(Boolean);
    return tokens.length > 1 && tokens.every((token) => hay.includes(token));
  });

  if (!q) return filtered;

  return filtered
    .map((item) => ({ item, score: scoreSearchItem(item, q) }))
    .sort((a, b) => b.score - a.score || a.item.title.localeCompare(b.item.title))
    .map(({ item }) => item);
}

export async function handleSearch(
  request: Request,
  env: { ASSETS?: { fetch: (request: Request) => Promise<Response> } },
  requestId?: string,
): Promise<Response> {
  const url = new URL(request.url);
  const qRaw = url.searchParams.get("q") || "";
  // Cap query length to keep filter work bounded (GET remains cacheable).
  const q = qRaw.length > 200 ? qRaw.slice(0, 200) : qRaw;
  const topic = (url.searchParams.get("topic") || "").slice(0, 80);
  const words = (url.searchParams.get("words") || "any").slice(0, 40);
  const limitRaw = Number(url.searchParams.get("limit") || "40");
  const limit = Math.min(100, Math.max(1, Number.isFinite(limitRaw) ? limitRaw : 40));

  const items = await loadSearchIndex(env);
  const filtered = filterSearchItems(items, { q, topic, words });
  const results = filtered.slice(0, limit).map((item) => ({
    id: item.id,
    title: item.title,
    href: item.href,
    excerpt: item.excerpt,
    topic: item.topic,
    wordCount: item.wordCount,
  }));

  const body: Record<string, unknown> = {
    ok: true,
    q,
    topic: normalizeTopic(topic),
    words: words || "any",
    total: filtered.length,
    count: results.length,
    results,
  };
  if (requestId) body.requestId = requestId;

  const headers: Record<string, string> = {
    "Content-Type": "application/json; charset=utf-8",
    // Public catalog — short cache helps TTFB without serving stale filters long.
    "Cache-Control": "public, max-age=300, stale-while-revalidate=3600",
  };
  if (requestId) headers["x-request-id"] = requestId;

  return new Response(JSON.stringify(body), {
    status: 200,
    headers,
  });
}
