/**
 * Lightweight JSON search over a baked static catalog (no Supabase).
 * Index: public/search-index.json (generated by scripts/generate-search-index.mjs).
 */

import bakedIndex from "../public/search-index.json";

export type SearchIndexItem = {
  id: string;
  title: string;
  href: string;
  excerpt: string;
  topic: string;
  wordCount: number;
  keywords?: string[];
};

export type SearchIndexFile = {
  generatedAt: string;
  version: number;
  items: SearchIndexItem[];
};

const TOPIC_ALIASES: Record<string, string> = {
  all: "All",
  "guides & hubs": "Guides & hubs",
  guides: "Guides & hubs",
  hubs: "Guides & hubs",
  exercise: "Exercise",
  exercises: "Exercise",
  nutrition: "Nutrition",
  diet: "Nutrition",
  health: "Health",
  lifestyle: "Lifestyle",
  supplements: "Supplements",
  treatment: "Treatment",
  treatments: "Treatment",
  "finances & benefits": "Finances & Benefits",
  finances: "Finances & Benefits",
  benefits: "Finances & Benefits",
  pip: "Finances & Benefits",
  "mental health": "Mental Health",
  "work & career": "Work & Career",
  work: "Work & Career",
  conditions: "Conditions",
  other: "Other",
};

function normalizeTopic(raw: string | undefined | null): string {
  if (!raw) return "All";
  const key = raw.trim().toLowerCase();
  return TOPIC_ALIASES[key] ?? raw;
}

function wordCountInBucket(count: number, words: string): boolean {
  if (!words || words === "any") return true;
  if (words === "under1000" || words === "under_1000") return count > 0 && count < 1000;
  if (words === "over1000" || words === "over_1000") return count >= 1000;
  return true;
}

export function getBakedSearchIndex(): SearchIndexFile {
  return bakedIndex as SearchIndexFile;
}

export async function loadSearchIndex(env: {
  ASSETS?: { fetch: (request: Request) => Promise<Response> };
}): Promise<SearchIndexItem[]> {
  if (env.ASSETS) {
    try {
      const res = await env.ASSETS.fetch(
        new Request("https://assets.local/search-index.json"),
      );
      if (res.ok) {
        const data = (await res.json()) as SearchIndexFile;
        if (Array.isArray(data.items) && data.items.length) return data.items;
      }
    } catch {
      // fall through to baked
    }
  }
  return getBakedSearchIndex().items;
}

export function filterSearchItems(
  items: SearchIndexItem[],
  opts: { q?: string; topic?: string; words?: string },
): SearchIndexItem[] {
  const topic = normalizeTopic(opts.topic);
  const words = (opts.words || "any").trim().toLowerCase();
  const q = (opts.q || "").trim().toLowerCase();

  return items.filter((item) => {
    if (topic !== "All" && item.topic !== topic) return false;
    if (!wordCountInBucket(item.wordCount, words)) return false;
    if (!q) return true;
    const hay = [item.title, item.excerpt, item.topic, ...(item.keywords || [])]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export async function handleSearch(
  request: Request,
  env: { ASSETS?: { fetch: (request: Request) => Promise<Response> } },
): Promise<Response> {
  const url = new URL(request.url);
  const q = url.searchParams.get("q") || "";
  const topic = url.searchParams.get("topic") || "";
  const words = url.searchParams.get("words") || "any";
  const limitRaw = Number(url.searchParams.get("limit") || "40");
  const limit = Math.min(100, Math.max(1, Number.isFinite(limitRaw) ? limitRaw : 40));

  const items = await loadSearchIndex(env);
  const filtered = filterSearchItems(items, { q, topic, words });
  const results = filtered.slice(0, limit).map((item) => ({
    id: item.id,
    title: item.title,
    href: item.href,
    excerpt: item.excerpt,
    topic: item.topic,
    wordCount: item.wordCount,
  }));

  return new Response(
    JSON.stringify({
      ok: true,
      q,
      topic: normalizeTopic(topic),
      words: words || "any",
      total: filtered.length,
      count: results.length,
      results,
    }),
    {
      status: 200,
      headers: {
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "public, max-age=300, stale-while-revalidate=3600",
      },
    },
  );
}
