
-- Update existing active sections with richer, more compelling content
UPDATE about_us_sections SET content = 'Living With Arthritis was born in 2020 from a deeply personal journey. After watching a beloved family member battle the frustration of fragmented care — months-long NHS waiting lists, conflicting advice, and a painful sense of isolation — our founder resolved to build what didn''t exist: a single, trusted platform where anyone affected by arthritis could find expert-led resources, compassionate community, and real hope. What started as a modest collection of articles has blossomed into a comprehensive health platform supporting over 10,000 people across all four nations of the United Kingdom, with partnerships spanning NHS trusts, chartered physiotherapists, and registered dietitians.', updated_at = now() WHERE title = 'Our Story';

UPDATE about_us_sections SET content = 'Arthritis is not a single disease — it encompasses over 100 distinct conditions affecting joints, bones, and connective tissues. In the UK alone, more than 10 million people live with some form of arthritis, including 15,000 children. Globally, the figure exceeds 350 million. It is the leading cause of chronic pain and physical disability in the developed world, costing the NHS an estimated £10 billion annually. Rheumatoid arthritis affects roughly 400,000 adults in Britain, while osteoarthritis — the most common form — impacts one in five people over 45. Despite this enormous burden, arthritis research receives just 3% of UK medical research funding. These are not abstract numbers; they represent parents who struggle to hold their children, workers forced into early retirement, and young people whose dreams are reshaped by daily pain.', updated_at = now() WHERE title = 'The Scale of Arthritis';

UPDATE about_us_sections SET content = 'We exist to fundamentally transform the lives of everyone touched by arthritis — those living with it, their families, carers, and employers. Our mission rests on four pillars: (1) Education — delivering clinically reviewed, plain-English guidance on symptoms, treatments, nutrition, and self-management; (2) Access — providing free virtual physiotherapy consultations to eliminate geographical and financial barriers; (3) Community — fostering peer support networks where shared experience becomes collective strength; and (4) Advocacy — campaigning for increased research funding, faster diagnosis pathways, and fairer access to biological therapies across the NHS. We believe that with the right information at the right time, every person with arthritis can live a fuller, more active life.', updated_at = now() WHERE title = 'Our Mission';

UPDATE about_us_sections SET content = 'Since 2020, we have built an evidence-based platform that includes free virtual physiotherapy consultations with HCPC-registered practitioners, an AI-powered symptom guide trained on NHS and NICE clinical guidelines, over 50 joint-specific exercise programmes designed by chartered physiotherapists, comprehensive anti-inflammatory nutrition resources developed with registered dietitians, and a growing library of 200+ articles covering every major arthritis type. Every tool, resource, and recommendation is cross-referenced with current NICE guidance (NG226 for OA, NG100 for RA), the British Society for Rheumatology standards, and peer-reviewed research from journals including The Lancet Rheumatology and Annals of the Rheumatic Diseases.', updated_at = now() WHERE title = 'What We''ve Built';

UPDATE about_us_sections SET content = 'Our vision is ambitious yet grounded in clear milestones: launching a mobile app for daily symptom tracking and self-management by 2026, establishing peer support groups in every NHS Integrated Care Board region, expanding our virtual physiotherapy service to include occupational therapy and psychological support, partnering with universities to fund patient-centred research, and advocating for arthritis to be recognised as a national health priority alongside cancer and cardiovascular disease. With every donation, volunteer hour, and shared story, we move closer to a future where arthritis no longer defines what someone can or cannot do.', updated_at = now() WHERE title = 'Looking Ahead';

-- Reactivate and improve the disabled sections with professional-quality content
UPDATE about_us_sections SET 
  is_active = true, 
  title = 'Our Commitment',
  content = 'Every piece of information on our platform is held to the highest clinical standards. We follow a rigorous editorial process: content is drafted by health writers with biomedical backgrounds, reviewed by practising rheumatologists or chartered physiotherapists, and updated quarterly to reflect the latest NICE guidelines and research. We are committed to accessibility — our website meets WCAG 2.1 AA standards, all resources are available free of charge, and we offer materials in multiple languages to serve the UK''s diverse communities. We are transparent about our funding, governance, and clinical partnerships because trust is the foundation of everything we do.',
  display_order = 3,
  updated_at = now()
WHERE id = '990b5ab5-987b-4617-93b1-a48f691aeaf9';

UPDATE about_us_sections SET 
  is_active = false,
  updated_at = now()
WHERE id = 'f21234ef-4038-4895-8574-c727a2d1dfc0';
