
UPDATE public.about_us_sections SET content = 'Living With Arthritis began with a simple question asked inside busy musculoskeletal clinics: why should expert arthritis care depend on a postcode, an income, or a place on a waiting list? Founded in 2020 by First Contact Practitioners, we set out to take the calm, evidence-based guidance people receive in the consulting room and make it open to anyone, anywhere in the UK — a quiet, clinical voice in a noisy internet.' WHERE title = 'Our Story';

UPDATE public.about_us_sections SET content = 'Arthritis is not one condition but a family of more than one hundred — osteoarthritis, rheumatoid arthritis, gout, psoriatic arthritis, ankylosing spondylitis, lupus and fibromyalgia among them. In the United Kingdom alone, around 10 million people live with a form of arthritis, and one in six adults reports persistent joint pain. It is the country''s leading cause of physical disability, yet remains one of its most underestimated conditions. The scale is the reason we exist.' WHERE title = 'The Scale of Arthritis';

UPDATE public.about_us_sections SET content = 'Our mission is to make expert, evidence-based arthritis care available to everyone in the UK — without cost, without gatekeeping, and without compromise. We do this through clinician-led virtual physiotherapy, anti-inflammatory nutrition guidance, joint-specific exercise programmes, an AI-assisted health companion and a community where lived experience is taken seriously. The promise is simple: the same calibre of guidance you would expect from a specialist clinic, freely available the moment you need it.' WHERE title = 'Our Mission';

UPDATE public.about_us_sections SET content = 'Every exercise, article and recommendation on this platform is reviewed by HCPC-registered physiotherapists and aligned with NICE clinical guidelines and peer-reviewed musculoskeletal research. We cite our sources, date our content, and update it as the evidence evolves. We do not accept advertising from pharmaceutical brands, and we hold no commercial conflicts of interest. Trust, for us, is not a marketing line — it is a clinical responsibility.' WHERE title = 'Our Commitment';

UPDATE public.about_us_sections SET content = 'In six years we have built one of the UK''s most comprehensive arthritis platforms: a virtual physiotherapy library covering every major joint, a Mediterranean-style nutrition hub, an AI health assistant, condition-specific guides for the most common forms of arthritis, an active flare-up toolkit, downloadable resources, and a peer community where members share what genuinely helps. More than 90,000 people have visited so far, and 97% report that what they found here was useful.' WHERE title = 'What We''ve Built';

UPDATE public.about_us_sections SET content = 'The next chapter is about depth and reach. We are expanding into condition-specific care pathways, multilingual content for under-served communities, a mobile companion to make daily self-management effortless, and research partnerships that turn real patient data into better guidance for everyone. Our long-term ambition is straightforward: that no one in the UK should face arthritis without expert support within easy reach. If our work matters to you, you can help us get there — by donating, volunteering, or simply passing it on.' WHERE title = 'Looking Ahead';
